UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "indie";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "electronic";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "experimental";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "post-rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "alternative";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "ambient";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "emo";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "indie rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "french";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "electronica";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "instrumental";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "idm";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "canadian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "minimal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "canada";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dubstep";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "progressive rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "female vocalists";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "hip-hop";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "stoner rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "punk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "noisecore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "japanese";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "psychedelic";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "folk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "acoustic";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "post-punk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "drone";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "hip hop";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "swedish";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "noise";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "rap";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "progressive";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "electro";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "downtempo";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "british";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "shoegaze";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "witch house";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "hard rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "stoner";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "christian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dub";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "american";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "industrial rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "new zealand";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "classic rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "90s";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "avant-garde";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "icelandic";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "grunge";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "soul";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "noise rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "techno";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "australian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "breakcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "under 2000 listeners";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "norwegian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "german";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "jazz";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dark ambient";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "usa";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "synthpop";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "8-bit";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "pop punk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "space rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "atmospheric";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "italian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "irish";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "funk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "depressive rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "psychedelic rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "artcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "chiptune";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "polish";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "punk rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "finnish";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "80s";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "jazzcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "comedy";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "gangsta rap";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "j-rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dutch";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "house";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "desert rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "rapcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "danish";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "all";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "straight edge";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "political";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "southern rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "visual kei";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "jrock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "funny";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "parody";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "avantgarde";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "mike patton";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "gothic";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "fusion";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "spanish";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "post-grunge";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "smoking music";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "sweden";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "hungarian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "electro-industrial";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "switzerland";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "nola";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "usa: louisiana";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "romanian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "russian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "ukrainian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "crossover";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "better than one direction";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "muppetcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "russell98";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "2000s";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "uk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "deutsch";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "freie musik";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "russia";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "bremen hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "brooklyn";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "post something";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "belgian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "neofolk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "lost children net label";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "nyhc";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "psytrance";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "lihc";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "arma angelus";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "belgium";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dark folk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dark hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "jewcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "local band";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "cascadian black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "experimental death metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "korean";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "progressive thrash metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "thrashcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "psychobilly";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "black death metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "dark metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "industrial death metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "stoner/doom";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "symphonic black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "technical thrash metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "1990s";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "defunct bands";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "nsbm";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "progmetal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "progressive-metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "zombiecore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "1st wave post-hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "euro8bitdance";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "gotta check";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "old school";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "brutal technical death metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "instrumental progressive metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "modern metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "old school swedish death metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "arnocore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "czech";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "epic black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "fusion metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "macedonian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "michigan";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "southern hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "the greatest band of all time";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "beatdown";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "beatdown hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "blackened sludge";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "brutal deathcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "extreme power metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "gore grind";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "technical deathcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "true black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "avantgarde metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "latvian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "new progressive";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "nintendo metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "3x6";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "glam rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "hard techno";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "rap metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "salsa metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "tiberian ass bastard folk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "united states";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "black doom metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "darkcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "neo-classical metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "better than radiohead";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "brazilian";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "goa";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "kansas city";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "scrubs";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "vegan";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "british black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "game remixers";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "gothic rock";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "industrial black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "pop rock brasil";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "ukrainian metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "bay area thrash metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "hundycore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "portuguese";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "psychedelic metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "rap nacional";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "russian death metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "sludge noise";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "spanish black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "technical";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "acoustic black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "belgian hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "black thrash metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "blackened thrash metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "death-thrash metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "green metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "grim and frostbitten";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "italian black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "japanese shoegaze";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "love metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "metal hardcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "noise punk";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "occult black metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "raw plant metal";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "spazzcore";
UPDATE metal_tags SET active = "false" WHERE source = 1 AND tag = "the most frostbitten and grim music from the very very very very very very inverted mountains of kxziiiimfghhhblaghl";

DELETE FROM metal_tags WHERE source = 1 AND tag LIKE '%metal%';